USE [master]
GO

/****** Object:  Database [Escuela2]    Script Date: 22/11/2018 16:33:02 ******/
CREATE DATABASE [Escuela2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Escuela2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Escuela2.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Escuela2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Escuela2_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Escuela2] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Escuela2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Escuela2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Escuela2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Escuela2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Escuela2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Escuela2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Escuela2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Escuela2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Escuela2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Escuela2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Escuela2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Escuela2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Escuela2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Escuela2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Escuela2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Escuela2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Escuela2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Escuela2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Escuela2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Escuela2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Escuela2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Escuela2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Escuela2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Escuela2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Escuela2] SET  MULTI_USER 
GO

ALTER DATABASE [Escuela2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Escuela2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Escuela2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Escuela2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Escuela2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Escuela2] SET  READ_WRITE 
GO

